# Generated by Django 5.1.6 on 2025-03-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_delete_author_remove_song_key_remove_song_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(null=True, upload_to='chordpro/'),
        ),
    ]
