# Generated by Django 5.1.6 on 2025-03-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_song_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
