# Generated by Django 5.1.6 on 2025-03-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_song_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='content',
            new_name='html_content',
        ),
    ]
