# Generated by Django 5.1.6 on 2025-03-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_song_title_author_alter_song_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='songs',
            field=models.ManyToManyField(related_name='songs', to='web.song'),
        ),
    ]
