# Generated by Django 5.1.6 on 2025-03-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_author_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='songs',
        ),
    ]
